// Comprehensive India Cities & States Dataset
// Dataset Source: Census of India / Administrative Divisions of India (Public Domain Data)

const INDIA_CITIES_DATASET = [
  // Tamil Nadu
  { city: 'Chennai', state: 'Tamil Nadu', aliases: ['Madras'] },
  { city: 'Coimbatore', state: 'Tamil Nadu', aliases: ['Kovai'] },
  { city: 'Madurai', state: 'Tamil Nadu' },
  { city: 'Tiruchirappalli', state: 'Tamil Nadu', aliases: ['Trichy', 'Tiruchi'] },
  { city: 'Salem', state: 'Tamil Nadu' },
  { city: 'Tirunelveli', state: 'Tamil Nadu', aliases: ['Nellai'] },
  { city: 'Tiruppur', state: 'Tamil Nadu', aliases: ['Tirupur'] },
  { city: 'Vellore', state: 'Tamil Nadu' },
  { city: 'Erode', state: 'Tamil Nadu' },
  { city: 'Thanjavur', state: 'Tamil Nadu', aliases: ['Tanjore'] },
  { city: 'Dindigul', state: 'Tamil Nadu' },
  { city: 'Kanchipuram', state: 'Tamil Nadu', aliases: ['Kanchi', 'Conjeevaram'] },
  { city: 'Nagercoil', state: 'Tamil Nadu' },
  { city: 'Cuddalore', state: 'Tamil Nadu' },
  { city: 'Karur', state: 'Tamil Nadu' },
  { city: 'Neyveli', state: 'Tamil Nadu' },
  { city: 'Kumbakonam', state: 'Tamil Nadu' },
  { city: 'Hosur', state: 'Tamil Nadu' },
  { city: 'Ambur', state: 'Tamil Nadu' },
  { city: 'Rajapalayam', state: 'Tamil Nadu' },
  { city: 'Pudukkottai', state: 'Tamil Nadu' },
  { city: 'Nagapattinam', state: 'Tamil Nadu' },
  { city: 'Ramanathapuram', state: 'Tamil Nadu' },
  { city: 'Thoothukudi', state: 'Tamil Nadu', aliases: ['Tuticorin'] },
  { city: 'Kanyakumari', state: 'Tamil Nadu' },
  { city: 'Ooty', state: 'Tamil Nadu', aliases: ['Udhagamandalam'] },
  { city: 'Kodaikanal', state: 'Tamil Nadu' },

  // Puducherry UT
  { city: 'Puducherry', state: 'Puducherry', aliases: ['Pondicherry', 'Pondy'] },
  { city: 'Karaikal', state: 'Puducherry' },
  { city: 'Mahe', state: 'Puducherry' },
  { city: 'Yanam', state: 'Puducherry' },

  // Karnataka
  { city: 'Bengaluru', state: 'Karnataka', aliases: ['Bangalore'] },
  { city: 'Mysuru', state: 'Karnataka', aliases: ['Mysore'] },
  { city: 'Mangaluru', state: 'Karnataka', aliases: ['Mangalore'] },
  { city: 'Hubballi', state: 'Karnataka', aliases: ['Hubli'] },
  { city: 'Dharwad', state: 'Karnataka' },
  { city: 'Belagavi', state: 'Karnataka', aliases: ['Belgaum'] },
  { city: 'Kalaburagi', state: 'Karnataka', aliases: ['Gulbarga'] },
  { city: 'Davanagere', state: 'Karnataka' },
  { city: 'Ballari', state: 'Karnataka', aliases: ['Bellary'] },
  { city: 'Vijayapura', state: 'Karnataka', aliases: ['Bijapur'] },
  { city: 'Shivamogga', state: 'Karnataka', aliases: ['Shimoga'] },
  { city: 'Tumakuru', state: 'Karnataka', aliases: ['Tumkur'] },
  { city: 'Raichur', state: 'Karnataka' },
  { city: 'Bidar', state: 'Karnataka' },
  { city: 'Hosapete', state: 'Karnataka', aliases: ['Hospet'] },
  { city: 'Gadag', state: 'Karnataka' },
  { city: 'Udupi', state: 'Karnataka' },
  { city: 'Hassan', state: 'Karnataka' },
  { city: 'Bhadravathi', state: 'Karnataka' },
  { city: 'Chitradurga', state: 'Karnataka' },
  { city: 'Kolar', state: 'Karnataka' },
  { city: 'Mandya', state: 'Karnataka' },
  { city: 'Chikkamagaluru', state: 'Karnataka', aliases: ['Chikmagalur'] },
  { city: 'Karwar', state: 'Karnataka' },

  // Kerala
  { city: 'Thiruvananthapuram', state: 'Kerala', aliases: ['Trivandrum'] },
  { city: 'Kochi', state: 'Kerala', aliases: ['Cochin', 'Ernakulam'] },
  { city: 'Kozhikode', state: 'Kerala', aliases: ['Calicut'] },
  { city: 'Thrissur', state: 'Kerala', aliases: ['Trichur'] },
  { city: 'Kollam', state: 'Kerala', aliases: ['Quilon'] },
  { city: 'Alappuzha', state: 'Kerala', aliases: ['Alleppey'] },
  { city: 'Palakkad', state: 'Kerala', aliases: ['Palghat'] },
  { city: 'Kannur', state: 'Kerala', aliases: ['Cannanore'] },
  { city: 'Kottayam', state: 'Kerala' },
  { city: 'Malappuram', state: 'Kerala' },
  { city: 'Manjeri', state: 'Kerala' },
  { city: 'Thalassery', state: 'Kerala' },
  { city: 'Ponnani', state: 'Kerala' },
  { city: 'Vatakara', state: 'Kerala' },
  { city: 'Kanhangad', state: 'Kerala' },
  { city: 'Payyanur', state: 'Kerala' },
  { city: 'Koyilandy', state: 'Kerala' },
  { city: 'Parappanangadi', state: 'Kerala' },
  { city: 'Kalamassery', state: 'Kerala' },
  { city: 'Neyyattinkara', state: 'Kerala' },
  { city: 'Muvattupuzha', state: 'Kerala' },

  // Maharashtra
  { city: 'Mumbai', state: 'Maharashtra', aliases: ['Bombay'] },
  { city: 'Pune', state: 'Maharashtra', aliases: ['Poona'] },
  { city: 'Nagpur', state: 'Maharashtra' },
  { city: 'Thane', state: 'Maharashtra' },
  { city: 'Pimpri-Chinchwad', state: 'Maharashtra' },
  { city: 'Nashik', state: 'Maharashtra', aliases: ['Nasik'] },
  { city: 'Kalyan-Dombivli', state: 'Maharashtra' },
  { city: 'Vasai-Virar', state: 'Maharashtra' },
  { city: 'Aurangabad', state: 'Maharashtra', aliases: ['Chhatrapati Sambhajinagar', 'Sambhajinagar'] },
  { city: 'Navi Mumbai', state: 'Maharashtra' },
  { city: 'Solapur', state: 'Maharashtra' },
  { city: 'Mira-Bhayandar', state: 'Maharashtra' },
  { city: 'Bhiwandi', state: 'Maharashtra' },
  { city: 'Amravati', state: 'Maharashtra' },
  { city: 'Nanded', state: 'Maharashtra' },
  { city: 'Kolhapur', state: 'Maharashtra' },
  { city: 'Ulhasnagar', state: 'Maharashtra' },
  { city: 'Sangli', state: 'Maharashtra' },
  { city: 'Malegaon', state: 'Maharashtra' },
  { city: 'Jalgaon', state: 'Maharashtra' },
  { city: 'Akola', state: 'Maharashtra' },
  { city: 'Latur', state: 'Maharashtra' },
  { city: 'Dhule', state: 'Maharashtra' },
  { city: 'Ahmednagar', state: 'Maharashtra', aliases: ['Ahilyanagar'] },
  { city: 'Chandrapur', state: 'Maharashtra' },
  { city: 'Parbhani', state: 'Maharashtra' },
  { city: 'Ichalkaranji', state: 'Maharashtra' },
  { city: 'Jalna', state: 'Maharashtra' },
  { city: 'Ambarnath', state: 'Maharashtra' },
  { city: 'Bhusawal', state: 'Maharashtra' },
  { city: 'Panvel', state: 'Maharashtra' },
  { city: 'Satara', state: 'Maharashtra' },
  { city: 'Beed', state: 'Maharashtra' },
  { city: 'Yavatmal', state: 'Maharashtra' },
  { city: 'Gondia', state: 'Maharashtra' },
  { city: 'Ratnagiri', state: 'Maharashtra' },

  // Telangana
  { city: 'Hyderabad', state: 'Telangana', aliases: ['Secunderabad'] },
  { city: 'Warangal', state: 'Telangana' },
  { city: 'Nizamabad', state: 'Telangana' },
  { city: 'Karimnagar', state: 'Telangana' },
  { city: 'Ramagundam', state: 'Telangana' },
  { city: 'Khammam', state: 'Telangana' },
  { city: 'Mahbubnagar', state: 'Telangana' },
  { city: 'Nalgonda', state: 'Telangana' },
  { city: 'Adilabad', state: 'Telangana' },
  { city: 'Suryapet', state: 'Telangana' },
  { city: 'Miryalaguda', state: 'Telangana' },
  { city: 'Siddipet', state: 'Telangana' },

  // Andhra Pradesh
  { city: 'Visakhapatnam', state: 'Andhra Pradesh', aliases: ['Vizag'] },
  { city: 'Vijayawada', state: 'Andhra Pradesh', aliases: ['Bezawada'] },
  { city: 'Guntur', state: 'Andhra Pradesh' },
  { city: 'Nellore', state: 'Andhra Pradesh' },
  { city: 'Kurnool', state: 'Andhra Pradesh' },
  { city: 'Rajahmundry', state: 'Andhra Pradesh', aliases: ['Rajamahendravaram'] },
  { city: 'Tirupati', state: 'Andhra Pradesh' },
  { city: 'Kakinada', state: 'Andhra Pradesh' },
  { city: 'Kadapa', state: 'Andhra Pradesh', aliases: ['Cuddapah'] },
  { city: 'Anantapur', state: 'Andhra Pradesh' },
  { city: 'Eluru', state: 'Andhra Pradesh' },
  { city: 'Vizianagaram', state: 'Andhra Pradesh' },
  { city: 'Ongole', state: 'Andhra Pradesh' },
  { city: 'Nandyal', state: 'Andhra Pradesh' },
  { city: 'Machilipatnam', state: 'Andhra Pradesh' },
  { city: 'Adoni', state: 'Andhra Pradesh' },
  { city: 'Tenali', state: 'Andhra Pradesh' },
  { city: 'Chittoor', state: 'Andhra Pradesh' },
  { city: 'Hindupur', state: 'Andhra Pradesh' },
  { city: 'Bhimavaram', state: 'Andhra Pradesh' },

  // Gujarat
  { city: 'Ahmedabad', state: 'Gujarat', aliases: ['Amdavad'] },
  { city: 'Surat', state: 'Gujarat' },
  { city: 'Vadodara', state: 'Gujarat', aliases: ['Baroda'] },
  { city: 'Rajkot', state: 'Gujarat' },
  { city: 'Bhavnagar', state: 'Gujarat' },
  { city: 'Jamnagar', state: 'Gujarat' },
  { city: 'Junagadh', state: 'Gujarat' },
  { city: 'Gandhinagar', state: 'Gujarat' },
  { city: 'Gandhidham', state: 'Gujarat' },
  { city: 'Nadiad', state: 'Gujarat' },
  { city: 'Anand', state: 'Gujarat' },
  { city: 'Morbi', state: 'Gujarat' },
  { city: 'Mehsana', state: 'Gujarat' },
  { city: 'Surendranagar', state: 'Gujarat' },
  { city: 'Bharuch', state: 'Gujarat' },
  { city: 'Vapi', state: 'Gujarat' },
  { city: 'Navsari', state: 'Gujarat' },
  { city: 'Veraval', state: 'Gujarat' },
  { city: 'Porbandar', state: 'Gujarat' },
  { city: 'Godhra', state: 'Gujarat' },
  { city: 'Bhuj', state: 'Gujarat' },

  // Madhya Pradesh
  { city: 'Indore', state: 'Madhya Pradesh' },
  { city: 'Bhopal', state: 'Madhya Pradesh' },
  { city: 'Jabalpur', state: 'Madhya Pradesh' },
  { city: 'Gwalior', state: 'Madhya Pradesh' },
  { city: 'Ujjain', state: 'Madhya Pradesh' },
  { city: 'Sagar', state: 'Madhya Pradesh' },
  { city: 'Dewas', state: 'Madhya Pradesh' },
  { city: 'Satna', state: 'Madhya Pradesh' },
  { city: 'Ratlam', state: 'Madhya Pradesh' },
  { city: 'Rewa', state: 'Madhya Pradesh' },
  { city: 'Murwara', state: 'Madhya Pradesh', aliases: ['Katni'] },
  { city: 'Singrauli', state: 'Madhya Pradesh' },
  { city: 'Burhanpur', state: 'Madhya Pradesh' },
  { city: 'Khandwa', state: 'Madhya Pradesh' },
  { city: 'Bhind', state: 'Madhya Pradesh' },
  { city: 'Chhindwara', state: 'Madhya Pradesh' },
  { city: 'Guna', state: 'Madhya Pradesh' },
  { city: 'Shivpuri', state: 'Madhya Pradesh' },
  { city: 'Vidisha', state: 'Madhya Pradesh' },

  // Rajasthan
  { city: 'Jaipur', state: 'Rajasthan' },
  { city: 'Jodhpur', state: 'Rajasthan' },
  { city: 'Kota', state: 'Rajasthan' },
  { city: 'Bikaner', state: 'Rajasthan' },
  { city: 'Ajmer', state: 'Rajasthan' },
  { city: 'Udaipur', state: 'Rajasthan' },
  { city: 'Bhilwara', state: 'Rajasthan' },
  { city: 'Alwar', state: 'Rajasthan' },
  { city: 'Bharatpur', state: 'Rajasthan' },
  { city: 'Sikar', state: 'Rajasthan' },
  { city: 'Pali', state: 'Rajasthan' },
  { city: 'Sri Ganganagar', state: 'Rajasthan' },
  { city: 'Kishangarh', state: 'Rajasthan' },
  { city: 'Barmer', state: 'Rajasthan' },
  { city: 'Hanumangarh', state: 'Rajasthan' },
  { city: 'Beawar', state: 'Rajasthan' },
  { city: 'Jhalawar', state: 'Rajasthan' },

  // Uttar Pradesh
  { city: 'Lucknow', state: 'Uttar Pradesh' },
  { city: 'Kanpur', state: 'Uttar Pradesh' },
  { city: 'Ghaziabad', state: 'Uttar Pradesh' },
  { city: 'Agra', state: 'Uttar Pradesh' },
  { city: 'Varanasi', state: 'Uttar Pradesh', aliases: ['Banaras', 'Kashi'] },
  { city: 'Meerut', state: 'Uttar Pradesh' },
  { city: 'Prayagraj', state: 'Uttar Pradesh', aliases: ['Allahabad'] },
  { city: 'Bareilly', state: 'Uttar Pradesh' },
  { city: 'Aligarh', state: 'Uttar Pradesh' },
  { city: 'Moradabad', state: 'Uttar Pradesh' },
  { city: 'Saharanpur', state: 'Uttar Pradesh' },
  { city: 'Gorakhpur', state: 'Uttar Pradesh' },
  { city: 'Noida', state: 'Uttar Pradesh' },
  { city: 'Greater Noida', state: 'Uttar Pradesh' },
  { city: 'Firozabad', state: 'Uttar Pradesh' },
  { city: 'Jhansi', state: 'Uttar Pradesh' },
  { city: 'Muzaffarnagar', state: 'Uttar Pradesh' },
  { city: 'Mathura', state: 'Uttar Pradesh' },
  { city: 'Budaun', state: 'Uttar Pradesh' },
  { city: 'Rampur', state: 'Uttar Pradesh' },
  { city: 'Shahjahanpur', state: 'Uttar Pradesh' },
  { city: 'Farrukhabad', state: 'Uttar Pradesh' },
  { city: 'Ayodhya', state: 'Uttar Pradesh', aliases: ['Faizabad'] },
  { city: 'Hapur', state: 'Uttar Pradesh' },
  { city: 'Etawah', state: 'Uttar Pradesh' },
  { city: 'Mirzapur', state: 'Uttar Pradesh' },
  { city: 'Bulandshahr', state: 'Uttar Pradesh' },

  // Uttarakhand
  { city: 'Dehradun', state: 'Uttarakhand' },
  { city: 'Haridwar', state: 'Uttarakhand' },
  { city: 'Roorkee', state: 'Uttarakhand' },
  { city: 'Haldwani', state: 'Uttarakhand', aliases: ['Haldwani-cum-Kathgodam'] },
  { city: 'Rudrapur', state: 'Uttarakhand' },
  { city: 'Kashipur', state: 'Uttarakhand' },
  { city: 'Rishikesh', state: 'Uttarakhand' },
  { city: 'Nainital', state: 'Uttarakhand' },

  // Assam
  { city: 'Guwahati', state: 'Assam', aliases: ['Gauhati'] },
  { city: 'Silchar', state: 'Assam' },
  { city: 'Dibrugarh', state: 'Assam' },
  { city: 'Jorhat', state: 'Assam' },
  { city: 'Nagaon', state: 'Assam' },
  { city: 'Tinsukia', state: 'Assam' },
  { city: 'Tezpur', state: 'Assam' },
  { city: 'Bongaigaon', state: 'Assam' },

  // Odisha
  { city: 'Bhubaneswar', state: 'Odisha' },
  { city: 'Cuttack', state: 'Odisha' },
  { city: 'Rourkela', state: 'Odisha' },
  { city: 'Berhampur', state: 'Odisha', aliases: ['Brahmapur'] },
  { city: 'Sambalpur', state: 'Odisha' },
  { city: 'Puri', state: 'Odisha' },
  { city: 'Balasore', state: 'Odisha', aliases: ['Baleshwar'] },
  { city: 'Bhadrak', state: 'Odisha' },
  { city: 'Baripada', state: 'Odisha' },

  // West Bengal
  { city: 'Kolkata', state: 'West Bengal', aliases: ['Calcutta'] },
  { city: 'Howrah', state: 'West Bengal' },
  { city: 'Asansol', state: 'West Bengal' },
  { city: 'Siliguri', state: 'West Bengal' },
  { city: 'Durgapur', state: 'West Bengal' },
  { city: 'Bardhaman', state: 'West Bengal', aliases: ['Burdwan'] },
  { city: 'Malda', state: 'West Bengal', aliases: ['English Bazar'] },
  { city: 'Kharagpur', state: 'West Bengal' },
  { city: 'Baharampur', state: 'West Bengal', aliases: ['Berhampore'] },
  { city: 'Habra', state: 'West Bengal' },
  { city: 'Shantipur', state: 'West Bengal' },
  { city: 'Darjeeling', state: 'West Bengal' },

  // Bihar
  { city: 'Patna', state: 'Bihar' },
  { city: 'Gaya', state: 'Bihar' },
  { city: 'Bhagalpur', state: 'Bihar' },
  { city: 'Muzaffarpur', state: 'Bihar' },
  { city: 'Purnia', state: 'Bihar' },
  { city: 'Darbhanga', state: 'Bihar' },
  { city: 'Bihar Sharif', state: 'Bihar' },
  { city: 'Arrah', state: 'Bihar' },
  { city: 'Begusarai', state: 'Bihar' },
  { city: 'Katihar', state: 'Bihar' },
  { city: 'Munger', state: 'Bihar' },

  // Jharkhand
  { city: 'Ranchi', state: 'Jharkhand' },
  { city: 'Jamshedpur', state: 'Jharkhand', aliases: ['Tatanagar'] },
  { city: 'Dhanbad', state: 'Jharkhand' },
  { city: 'Bokaro', state: 'Jharkhand', aliases: ['Bokaro Steel City'] },
  { city: 'Deoghar', state: 'Jharkhand' },
  { city: 'Phusro', state: 'Jharkhand' },
  { city: 'Hazaribagh', state: 'Jharkhand' },
  { city: 'Giridih', state: 'Jharkhand' },

  // Punjab
  { city: 'Ludhiana', state: 'Punjab' },
  { city: 'Amritsar', state: 'Punjab' },
  { city: 'Jalandhar', state: 'Punjab' },
  { city: 'Patiala', state: 'Punjab' },
  { city: 'Bathinda', state: 'Punjab' },
  { city: 'Mohali', state: 'Punjab', aliases: ['SAS Nagar', 'Sahibzada Ajit Singh Nagar'] },
  { city: 'Pathankot', state: 'Punjab' },
  { city: 'Hoshiarpur', state: 'Punjab' },
  { city: 'Batala', state: 'Punjab' },
  { city: 'Moga', state: 'Punjab' },

  // Haryana
  { city: 'Faridabad', state: 'Haryana' },
  { city: 'Gurugram', state: 'Haryana', aliases: ['Gurgaon'] },
  { city: 'Panipat', state: 'Haryana' },
  { city: 'Ambala', state: 'Haryana' },
  { city: 'Yamunanagar', state: 'Haryana' },
  { city: 'Rohtak', state: 'Haryana' },
  { city: 'Hisar', state: 'Haryana' },
  { city: 'Karnal', state: 'Haryana' },
  { city: 'Sonipat', state: 'Haryana' },
  { city: 'Panchkula', state: 'Haryana' },

  // Himachal Pradesh
  { city: 'Shimla', state: 'Himachal Pradesh', aliases: ['Simla'] },
  { city: 'Dharamshala', state: 'Himachal Pradesh' },
  { city: 'Manali', state: 'Himachal Pradesh' },
  { city: 'Solan', state: 'Himachal Pradesh' },
  { city: 'Mandi', state: 'Himachal Pradesh' },
  { city: 'Baddi', state: 'Himachal Pradesh' },
  { city: 'Kullu', state: 'Himachal Pradesh' },

  // Chhattisgarh
  { city: 'Raipur', state: 'Chhattisgarh' },
  { city: 'Bhilai', state: 'Chhattisgarh' },
  { city: 'Bilaspur', state: 'Chhattisgarh' },
  { city: 'Korba', state: 'Chhattisgarh' },
  { city: 'Rajnandgaon', state: 'Chhattisgarh' },
  { city: 'Raigarh', state: 'Chhattisgarh' },
  { city: 'Jagdalpur', state: 'Chhattisgarh' },

  // Goa
  { city: 'Panaji', state: 'Goa', aliases: ['Panjim'] },
  { city: 'Margao', state: 'Goa', aliases: ['Madgaon'] },
  { city: 'Vasco da Gama', state: 'Goa', aliases: ['Vasco'] },
  { city: 'Mapusa', state: 'Goa' },
  { city: 'Ponda', state: 'Goa' },

  // Jammu & Kashmir UT
  { city: 'Srinagar', state: 'Jammu and Kashmir' },
  { city: 'Jammu', state: 'Jammu and Kashmir' },
  { city: 'Anantnag', state: 'Jammu and Kashmir' },
  { city: 'Udhampur', state: 'Jammu and Kashmir' },
  { city: 'Baramulla', state: 'Jammu and Kashmir' },

  // Ladakh UT
  { city: 'Leh', state: 'Ladakh' },
  { city: 'Kargil', state: 'Ladakh' },

  // Chandigarh UT
  { city: 'Chandigarh', state: 'Chandigarh' },

  // Delhi UT
  { city: 'Delhi', state: 'Delhi' },
  { city: 'New Delhi', state: 'Delhi' },

  // North-East States
  { city: 'Agartala', state: 'Tripura' },
  { city: 'Shillong', state: 'Meghalaya' },
  { city: 'Imphal', state: 'Manipur' },
  { city: 'Aizawl', state: 'Mizoram' },
  { city: 'Kohima', state: 'Nagaland' },
  { city: 'Dimapur', state: 'Nagaland' },
  { city: 'Gangtok', state: 'Sikkim' },
  { city: 'Itanagar', state: 'Arunachal Pradesh' },

  // Union Territories (Island & Coastal)
  { city: 'Port Blair', state: 'Andaman and Nicobar Islands' },
  { city: 'Kavaratti', state: 'Lakshadweep' },
  { city: 'Silvassa', state: 'Dadra and Nagar Haveli and Daman and Diu' },
  { city: 'Daman', state: 'Dadra and Nagar Haveli and Daman and Diu' },
  { city: 'Diu', state: 'Dadra and Nagar Haveli and Daman and Diu' }
];

if (typeof window !== 'undefined') {
  window.INDIA_CITIES_DATASET = INDIA_CITIES_DATASET;
}
